### PR TITLE
Fix downloading by using http instead of https

### PR DESCRIPTION
**Pull request by ids1024**
I'm still having other issues, but I think this fixed the downloading part.

### CODE REVIEW

**Comment by alberthdev** [comment]
This may not work anymore... see my [comment](https://github.com/alberthdev/wxwabbitemu/issues/2#issuecomment-219726524) in issue #2.

**Comment by ids1024** [comment]
It seems you're right. It's odd though, because I thought I had downloaded one of these files using the link when I wrote this PR (in my browser). Indeed, I have the file on my computer. But it just gives a 403 now in the same browser...

**Comment by alberthdev** [comment]
Was the file you downloaded valid? Or did wxWabbitemu crash immediately after?

**Comment by ids1024** [comment]
The one I downloaded in wxwabbitemu led to a message that the rom was corrupted, suggesting it probably downloaded a 403 page instead of a rom. But I successfully downloaded a rom in my browser using the link from the code (which isn't working now). Anyway, this PR doesn't work, and I think it is broken in wabbitemu too.

**Pull request closed without merging**
